### PR TITLE
Turn on verbose mode by default (but allow the user to turn off verbose mode by passing the `verbose: false` plugin input)

### PR DESCRIPTION
**Pull request by DilumAluthge**
I personally think that the error messages are inscrutable unless you also have the verbose output.

cc: @maleadt

### CODE REVIEW

**Comment by maleadt** [comment]
Not a great solution to https://github.com/staticfloat/Sandbox.jl/issues/69, but LGTM I guess.

**Comment by DilumAluthge** [comment]
@staticfloat Any objection to this? I figure that since this is just for CI, it's not a big deal to make the logs more verbose, since it will get collapsed in a collapsible section anyway.

**Comment by staticfloat** [comment]
How about we check to see if the command failed in less than 5 seconds, and if it did (and verbose was not set) we auto-rerun with verbose set?

**Comment by DilumAluthge** [comment]
I like it!

**Comment by DilumAluthge** [comment]
I think that my ideal solution to https://github.com/staticfloat/Sandbox.jl/issues/69 would be to modify `sandbox.c` as follows:

If verbose mode is on, then print each of the debugging messages to stderr.

If verbose mode is off, then instead of printing each of the debugging messages to stderr, print it to some kind of internal buffer. If all of the `check` assertions pass, then this buffer is discarded when the `sandbox` process exits. However, if a `check` assertion fails, then, before the `sandbox` process exits, we print all of the contents of the buffer to stderr.

**Comment by DilumAluthge** [comment]
Bump @staticfloat @maleadt.

How do we want to move forward?

**Comment by DilumAluthge** [comment]
Closing as stale

**Pull request closed without merging**
